version: "3.8"

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    networks:
      - app

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - app

volumes:
  mongo-data:

networks:
  app:
    driver: bridge