all: main.o findAnagram.o addLetters.o replace.o sortSentences.o
	gcc main.o findAnagram.o addLetters.o replace.o sortSentences.o -o program

main.o: main.c
	gcc -c main.c

findAnagram.o: findAnagram.c
	gcc -c findAnagram.c

addLetters.o: addLetters.c
	gcc -c addLetters.c

replace.o: replace.c
	gcc -c replace.c

sortSentences.o: sortSentences.c
	gcc -c sortSentences.c